//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestOrderingApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class engUS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal engUS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestOrderingApp.engUS", typeof(engUS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below are all logged events:.
        /// </summary>
        internal static string Bitacora_instrucciones {
            get {
                return ResourceManager.GetString("Bitacora_instrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Bitacora_titulo {
            get {
                return ResourceManager.GetString("Bitacora_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish Category.
        /// </summary>
        internal static string Columna_Categoria {
            get {
                return ResourceManager.GetString("Columna_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish ID.
        /// </summary>
        internal static string Columna_IDPlato {
            get {
                return ResourceManager.GetString("Columna_IDPlato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish Name.
        /// </summary>
        internal static string Columna_NombrePlato {
            get {
                return ResourceManager.GetString("Columna_NombrePlato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Columna_Precio {
            get {
                return ResourceManager.GetString("Columna_Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Columna_Seleccionar {
            get {
                return ResourceManager.GetString("Columna_Seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string D_buttonBitacora {
            get {
                return ResourceManager.GetString("D_buttonBitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish Categories.
        /// </summary>
        internal static string D_conCatPlato {
            get {
                return ResourceManager.GetString("D_conCatPlato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        internal static string D_conCliente {
            get {
                return ResourceManager.GetString("D_conCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        internal static string D_conExtras {
            get {
                return ResourceManager.GetString("D_conExtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dishes.
        /// </summary>
        internal static string D_conPlato {
            get {
                return ResourceManager.GetString("D_conPlato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dishes per Restaurant.
        /// </summary>
        internal static string D_conPlatoRest {
            get {
                return ResourceManager.GetString("D_conPlatoRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        internal static string D_conRestaurante {
            get {
                return ResourceManager.GetString("D_conRestaurante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string D_ConsultarBtn {
            get {
                return ResourceManager.GetString("D_ConsultarBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish Category.
        /// </summary>
        internal static string D_regCatPlato {
            get {
                return ResourceManager.GetString("D_regCatPlato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string D_regCliente {
            get {
                return ResourceManager.GetString("D_regCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        internal static string D_regExtra {
            get {
                return ResourceManager.GetString("D_regExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string D_RegistrarBtn {
            get {
                return ResourceManager.GetString("D_RegistrarBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish.
        /// </summary>
        internal static string D_regPlato {
            get {
                return ResourceManager.GetString("D_regPlato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dishes per Restaurant.
        /// </summary>
        internal static string D_regPlatoRest {
            get {
                return ResourceManager.GetString("D_regPlatoRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        internal static string D_regRestaurante {
            get {
                return ResourceManager.GetString("D_regRestaurante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected Users:.
        /// </summary>
        internal static string D_UsuCuenta {
            get {
                return ResourceManager.GetString("D_UsuCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Estado1 {
            get {
                return ResourceManager.GetString("Estado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string Estado2 {
            get {
                return ResourceManager.GetString("Estado2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F: Feminine.
        /// </summary>
        internal static string Genero1 {
            get {
                return ResourceManager.GetString("Genero1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M: Masculine.
        /// </summary>
        internal static string Genero2 {
            get {
                return ResourceManager.GetString("Genero2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O: other.
        /// </summary>
        internal static string Genero3 {
            get {
                return ResourceManager.GetString("Genero3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string reg_boton {
            get {
                return ResourceManager.GetString("reg_boton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading resources.
        /// </summary>
        internal static string Reg_Cargando {
            get {
                return ResourceManager.GetString("Reg_Cargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on Data Base.
        /// </summary>
        internal static string Reg_ErrorDataBase {
            get {
                return ResourceManager.GetString("Reg_ErrorDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must fill out all the spaces with the correct format!.
        /// </summary>
        internal static string Reg_ErrorFaltaInfo {
            get {
                return ResourceManager.GetString("Reg_ErrorFaltaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It most be a positive number.
        /// </summary>
        internal static string Reg_ErrorNoInt {
            get {
                return ResourceManager.GetString("Reg_ErrorNoInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The indicated ID does not exist!.
        /// </summary>
        internal static string Reg_IdNoExiste {
            get {
                return ResourceManager.GetString("Reg_IdNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Id already exists!.
        /// </summary>
        internal static string Reg_IdYaExiste {
            get {
                return ResourceManager.GetString("Reg_IdYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Description:.
        /// </summary>
        internal static string regCat_descripcion {
            get {
                return ResourceManager.GetString("regCat_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category availability:.
        /// </summary>
        internal static string regCat_estado {
            get {
                return ResourceManager.GetString("regCat_estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category identification:.
        /// </summary>
        internal static string regCat_id {
            get {
                return ResourceManager.GetString("regCat_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out all the sections to register a category..
        /// </summary>
        internal static string regCat_instrucciones {
            get {
                return ResourceManager.GetString("regCat_instrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish Category Registration Form.
        /// </summary>
        internal static string regCat_titulo {
            get {
                return ResourceManager.GetString("regCat_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client first last name:.
        /// </summary>
        internal static string regCliente_apellido1 {
            get {
                return ResourceManager.GetString("regCliente_apellido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client second last name:.
        /// </summary>
        internal static string regCliente_apellido2 {
            get {
                return ResourceManager.GetString("regCliente_apellido2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client gender:.
        /// </summary>
        internal static string regCliente_genero {
            get {
                return ResourceManager.GetString("regCliente_genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client identification:.
        /// </summary>
        internal static string regCliente_id {
            get {
                return ResourceManager.GetString("regCliente_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out all the sections to register a client..
        /// </summary>
        internal static string regCliente_instrucciones {
            get {
                return ResourceManager.GetString("regCliente_instrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Date of Birth:.
        /// </summary>
        internal static string regCliente_nacimiento {
            get {
                return ResourceManager.GetString("regCliente_nacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client name:.
        /// </summary>
        internal static string regCliente_nombre {
            get {
                return ResourceManager.GetString("regCliente_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Registration Form.
        /// </summary>
        internal static string regCliente_titulo {
            get {
                return ResourceManager.GetString("regCliente_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra description:.
        /// </summary>
        internal static string regExtra_descripcion {
            get {
                return ResourceManager.GetString("regExtra_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra availability:.
        /// </summary>
        internal static string regExtra_estado {
            get {
                return ResourceManager.GetString("regExtra_estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra identification:.
        /// </summary>
        internal static string regExtra_id {
            get {
                return ResourceManager.GetString("regExtra_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish Category ID:.
        /// </summary>
        internal static string regExtra_idCat {
            get {
                return ResourceManager.GetString("regExtra_idCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out all the sections to register an extra..
        /// </summary>
        internal static string regExtra_instrucciones {
            get {
                return ResourceManager.GetString("regExtra_instrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra price:.
        /// </summary>
        internal static string regExtra_precio {
            get {
                return ResourceManager.GetString("regExtra_precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Registration Form.
        /// </summary>
        internal static string regExtra_titulo {
            get {
                return ResourceManager.GetString("regExtra_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must register a dish category first!.
        /// </summary>
        internal static string regPlato_ErrorCat {
            get {
                return ResourceManager.GetString("regPlato_ErrorCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish identification:.
        /// </summary>
        internal static string regPlato_id {
            get {
                return ResourceManager.GetString("regPlato_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish Category ID:.
        /// </summary>
        internal static string regPlato_idCat {
            get {
                return ResourceManager.GetString("regPlato_idCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out all the sections to register a dish..
        /// </summary>
        internal static string regPlato_instrucciones {
            get {
                return ResourceManager.GetString("regPlato_instrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish name:.
        /// </summary>
        internal static string regPlato_nombre {
            get {
                return ResourceManager.GetString("regPlato_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish price:.
        /// </summary>
        internal static string regPlato_precio {
            get {
                return ResourceManager.GetString("regPlato_precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish Registration Form.
        /// </summary>
        internal static string regPlato_titulo {
            get {
                return ResourceManager.GetString("regPlato_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate.
        /// </summary>
        internal static string regPlatoRest_asociar {
            get {
                return ResourceManager.GetString("regPlatoRest_asociar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must register a dish first!.
        /// </summary>
        internal static string regPlatoRest_ErrorNoPlat {
            get {
                return ResourceManager.GetString("regPlatoRest_ErrorNoPlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must register a restaurant first!.
        /// </summary>
        internal static string regPlatoRest_ErrorNoRest {
            get {
                return ResourceManager.GetString("regPlatoRest_ErrorNoRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a restaurant first!.
        /// </summary>
        internal static string regPlatoRest_ErrorRest {
            get {
                return ResourceManager.GetString("regPlatoRest_ErrorRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a restaurant and the dishes to be associated..
        /// </summary>
        internal static string regPlatoRest_instrucciones {
            get {
                return ResourceManager.GetString("regPlatoRest_instrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one dish..
        /// </summary>
        internal static string regPlatoRest_M1_info {
            get {
                return ResourceManager.GetString("regPlatoRest_M1_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Selecction.
        /// </summary>
        internal static string regPlatoRest_M1_tipo {
            get {
                return ResourceManager.GetString("regPlatoRest_M1_tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only 10 dishes can be associated per registration..
        /// </summary>
        internal static string regPlatoRest_M2_info {
            get {
                return ResourceManager.GetString("regPlatoRest_M2_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection limit exceeded.
        /// </summary>
        internal static string regPlatoRest_M2_tipo {
            get {
                return ResourceManager.GetString("regPlatoRest_M2_tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected.
        /// </summary>
        internal static string regPlatoRest_M3_info1 {
            get {
                return ResourceManager.GetString("regPlatoRest_M3_info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dishes. Want to add more? The maximum is 10..
        /// </summary>
        internal static string regPlatoRest_M3_info2 {
            get {
                return ResourceManager.GetString("regPlatoRest_M3_info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional selection.
        /// </summary>
        internal static string regPlatoRest_M3_tipo {
            get {
                return ResourceManager.GetString("regPlatoRest_M3_tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected 10 dishes. 10 is the maximun. Do you want to register the association? Select No to change your selection of dishes..
        /// </summary>
        internal static string regPlatoRest_M4_info {
            get {
                return ResourceManager.GetString("regPlatoRest_M4_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selección con límite máximo.
        /// </summary>
        internal static string regPlatoRest_M4_tipo {
            get {
                return ResourceManager.GetString("regPlatoRest_M4_tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dishes associated correctly!.
        /// </summary>
        internal static string regPlatoRest_M5_info {
            get {
                return ResourceManager.GetString("regPlatoRest_M5_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful association.
        /// </summary>
        internal static string regPlatoRest_M5_tipo {
            get {
                return ResourceManager.GetString("regPlatoRest_M5_tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available dishes:.
        /// </summary>
        internal static string regPlatoRest_platos {
            get {
                return ResourceManager.GetString("regPlatoRest_platos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated dishes:.
        /// </summary>
        internal static string regPlatoRest_platosAso {
            get {
                return ResourceManager.GetString("regPlatoRest_platosAso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available restaurants:.
        /// </summary>
        internal static string regPlatoRest_restaurante {
            get {
                return ResourceManager.GetString("regPlatoRest_restaurante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish per Restaurant Registration Form.
        /// </summary>
        internal static string regPlatoRest_titulo {
            get {
                return ResourceManager.GetString("regPlatoRest_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant address:.
        /// </summary>
        internal static string regRest_direccion {
            get {
                return ResourceManager.GetString("regRest_direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant availability:.
        /// </summary>
        internal static string regRest_estado {
            get {
                return ResourceManager.GetString("regRest_estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant identification:.
        /// </summary>
        internal static string regRest_id {
            get {
                return ResourceManager.GetString("regRest_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out all the sections to register a restaurant..
        /// </summary>
        internal static string regRest_instrucciones {
            get {
                return ResourceManager.GetString("regRest_instrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant name:.
        /// </summary>
        internal static string regRest_nombre {
            get {
                return ResourceManager.GetString("regRest_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant phone number:.
        /// </summary>
        internal static string regRest_telefono {
            get {
                return ResourceManager.GetString("regRest_telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Registration Form.
        /// </summary>
        internal static string regRest_titulo {
            get {
                return ResourceManager.GetString("regRest_titulo", resourceCulture);
            }
        }
    }
}
