//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestOrderingApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class esCR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal esCR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestOrderingApp.esCR", typeof(esCR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A continuación se muestran todos los eventos registrados:.
        /// </summary>
        internal static string Bitacora_instrucciones {
            get {
                return ResourceManager.GetString("Bitacora_instrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitácora.
        /// </summary>
        internal static string Bitacora_titulo {
            get {
                return ResourceManager.GetString("Bitacora_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        internal static string Columna_Categoria {
            get {
                return ResourceManager.GetString("Columna_Categoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id del plato.
        /// </summary>
        internal static string Columna_IDPlato {
            get {
                return ResourceManager.GetString("Columna_IDPlato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del plato.
        /// </summary>
        internal static string Columna_NombrePlato {
            get {
                return ResourceManager.GetString("Columna_NombrePlato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio.
        /// </summary>
        internal static string Columna_Precio {
            get {
                return ResourceManager.GetString("Columna_Precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        internal static string Columna_Seleccionar {
            get {
                return ResourceManager.GetString("Columna_Seleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitácora.
        /// </summary>
        internal static string D_buttonBitacora {
            get {
                return ResourceManager.GetString("D_buttonBitacora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorías de Platos.
        /// </summary>
        internal static string D_conCatPlato {
            get {
                return ResourceManager.GetString("D_conCatPlato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        internal static string D_conCliente {
            get {
                return ResourceManager.GetString("D_conCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        internal static string D_conExtras {
            get {
                return ResourceManager.GetString("D_conExtras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platos.
        /// </summary>
        internal static string D_conPlato {
            get {
                return ResourceManager.GetString("D_conPlato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platos por Restaurante.
        /// </summary>
        internal static string D_conPlatoRest {
            get {
                return ResourceManager.GetString("D_conPlatoRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurantes.
        /// </summary>
        internal static string D_conRestaurante {
            get {
                return ResourceManager.GetString("D_conRestaurante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultar.
        /// </summary>
        internal static string D_ConsultarBtn {
            get {
                return ResourceManager.GetString("D_ConsultarBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría de Plato.
        /// </summary>
        internal static string D_regCatPlato {
            get {
                return ResourceManager.GetString("D_regCatPlato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        internal static string D_regCliente {
            get {
                return ResourceManager.GetString("D_regCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        internal static string D_regExtra {
            get {
                return ResourceManager.GetString("D_regExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar.
        /// </summary>
        internal static string D_RegistrarBtn {
            get {
                return ResourceManager.GetString("D_RegistrarBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plato.
        /// </summary>
        internal static string D_regPlato {
            get {
                return ResourceManager.GetString("D_regPlato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platos por Restaurante.
        /// </summary>
        internal static string D_regPlatoRest {
            get {
                return ResourceManager.GetString("D_regPlatoRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurante.
        /// </summary>
        internal static string D_regRestaurante {
            get {
                return ResourceManager.GetString("D_regRestaurante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios Conectados:.
        /// </summary>
        internal static string D_UsuCuenta {
            get {
                return ResourceManager.GetString("D_UsuCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string Estado1 {
            get {
                return ResourceManager.GetString("Estado1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        internal static string Estado2 {
            get {
                return ResourceManager.GetString("Estado2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F: Femenino.
        /// </summary>
        internal static string Genero1 {
            get {
                return ResourceManager.GetString("Genero1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M: Masculino.
        /// </summary>
        internal static string Genero2 {
            get {
                return ResourceManager.GetString("Genero2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O: otro.
        /// </summary>
        internal static string Genero3 {
            get {
                return ResourceManager.GetString("Genero3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar.
        /// </summary>
        internal static string reg_boton {
            get {
                return ResourceManager.GetString("reg_boton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargardo Recursos.
        /// </summary>
        internal static string Reg_Cargando {
            get {
                return ResourceManager.GetString("Reg_Cargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error de Base de datos.
        /// </summary>
        internal static string Reg_ErrorDataBase {
            get {
                return ResourceManager.GetString("Reg_ErrorDataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe llenar todos los apartados con el formato correcto!.
        /// </summary>
        internal static string Reg_ErrorFaltaInfo {
            get {
                return ResourceManager.GetString("Reg_ErrorFaltaInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe ser un numero entero positivo!.
        /// </summary>
        internal static string Reg_ErrorNoInt {
            get {
                return ResourceManager.GetString("Reg_ErrorNoInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ID digitada no existe!.
        /// </summary>
        internal static string Reg_IdNoExiste {
            get {
                return ResourceManager.GetString("Reg_IdNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ID digitada ya existe!.
        /// </summary>
        internal static string Reg_IdYaExiste {
            get {
                return ResourceManager.GetString("Reg_IdYaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción de la categoría:.
        /// </summary>
        internal static string regCat_descripcion {
            get {
                return ResourceManager.GetString("regCat_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado de la categoría:.
        /// </summary>
        internal static string regCat_estado {
            get {
                return ResourceManager.GetString("regCat_estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación de la categoría:.
        /// </summary>
        internal static string regCat_id {
            get {
                return ResourceManager.GetString("regCat_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llene todos los apartados para registrar una categoría..
        /// </summary>
        internal static string regCat_instrucciones {
            get {
                return ResourceManager.GetString("regCat_instrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de Categoría de Plato.
        /// </summary>
        internal static string regCat_titulo {
            get {
                return ResourceManager.GetString("regCat_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer Apellido del Cliente:.
        /// </summary>
        internal static string regCliente_apellido1 {
            get {
                return ResourceManager.GetString("regCliente_apellido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo Apellido del Cliente:.
        /// </summary>
        internal static string regCliente_apellido2 {
            get {
                return ResourceManager.GetString("regCliente_apellido2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genero del cliente:.
        /// </summary>
        internal static string regCliente_genero {
            get {
                return ResourceManager.GetString("regCliente_genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación del Cliente:.
        /// </summary>
        internal static string regCliente_id {
            get {
                return ResourceManager.GetString("regCliente_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llene todos los apartados para registrar un cliente..
        /// </summary>
        internal static string regCliente_instrucciones {
            get {
                return ResourceManager.GetString("regCliente_instrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de nacimineto:.
        /// </summary>
        internal static string regCliente_nacimiento {
            get {
                return ResourceManager.GetString("regCliente_nacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del cliente:.
        /// </summary>
        internal static string regCliente_nombre {
            get {
                return ResourceManager.GetString("regCliente_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de Cliente.
        /// </summary>
        internal static string regCliente_titulo {
            get {
                return ResourceManager.GetString("regCliente_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción del Extra:.
        /// </summary>
        internal static string regExtra_descripcion {
            get {
                return ResourceManager.GetString("regExtra_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado del Extra:.
        /// </summary>
        internal static string regExtra_estado {
            get {
                return ResourceManager.GetString("regExtra_estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación del Extra:.
        /// </summary>
        internal static string regExtra_id {
            get {
                return ResourceManager.GetString("regExtra_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID de la Categoría del Extra:.
        /// </summary>
        internal static string regExtra_idCat {
            get {
                return ResourceManager.GetString("regExtra_idCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llene todos los apartados para registrar un extra..
        /// </summary>
        internal static string regExtra_instrucciones {
            get {
                return ResourceManager.GetString("regExtra_instrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio del Extra:.
        /// </summary>
        internal static string regExtra_precio {
            get {
                return ResourceManager.GetString("regExtra_precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de Extra.
        /// </summary>
        internal static string regExtra_titulo {
            get {
                return ResourceManager.GetString("regExtra_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe registrar una categoría de plato primero!.
        /// </summary>
        internal static string regPlato_ErrorCat {
            get {
                return ResourceManager.GetString("regPlato_ErrorCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indentificación del Plato:.
        /// </summary>
        internal static string regPlato_id {
            get {
                return ResourceManager.GetString("regPlato_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID de la Categoria del Plato:.
        /// </summary>
        internal static string regPlato_idCat {
            get {
                return ResourceManager.GetString("regPlato_idCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llene todos los apartados para registrar un plato..
        /// </summary>
        internal static string regPlato_instrucciones {
            get {
                return ResourceManager.GetString("regPlato_instrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Plato:.
        /// </summary>
        internal static string regPlato_nombre {
            get {
                return ResourceManager.GetString("regPlato_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio del Plato:.
        /// </summary>
        internal static string regPlato_precio {
            get {
                return ResourceManager.GetString("regPlato_precio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de Plato.
        /// </summary>
        internal static string regPlato_titulo {
            get {
                return ResourceManager.GetString("regPlato_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociar.
        /// </summary>
        internal static string regPlatoRest_asociar {
            get {
                return ResourceManager.GetString("regPlatoRest_asociar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe registrar un plato primero!.
        /// </summary>
        internal static string regPlatoRest_ErrorNoPlat {
            get {
                return ResourceManager.GetString("regPlatoRest_ErrorNoPlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe registrar un restaurante primero!.
        /// </summary>
        internal static string regPlatoRest_ErrorNoRest {
            get {
                return ResourceManager.GetString("regPlatoRest_ErrorNoRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar un restaurante.
        /// </summary>
        internal static string regPlatoRest_ErrorRest {
            get {
                return ResourceManager.GetString("regPlatoRest_ErrorRest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un restaurante y los platos a asociar..
        /// </summary>
        internal static string regPlatoRest_instrucciones {
            get {
                return ResourceManager.GetString("regPlatoRest_instrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar al menos un plato..
        /// </summary>
        internal static string regPlatoRest_M1_info {
            get {
                return ResourceManager.GetString("regPlatoRest_M1_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selección requerida.
        /// </summary>
        internal static string regPlatoRest_M1_tipo {
            get {
                return ResourceManager.GetString("regPlatoRest_M1_tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo se pueden asociar 10 platos por registro..
        /// </summary>
        internal static string regPlatoRest_M2_info {
            get {
                return ResourceManager.GetString("regPlatoRest_M2_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Límite de selección sobrepasado.
        /// </summary>
        internal static string regPlatoRest_M2_tipo {
            get {
                return ResourceManager.GetString("regPlatoRest_M2_tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted ha seleccionado.
        /// </summary>
        internal static string regPlatoRest_M3_info1 {
            get {
                return ResourceManager.GetString("regPlatoRest_M3_info1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to platos. ¿Desea agregar más? El máximo es 10..
        /// </summary>
        internal static string regPlatoRest_M3_info2 {
            get {
                return ResourceManager.GetString("regPlatoRest_M3_info2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selección adicional.
        /// </summary>
        internal static string regPlatoRest_M3_tipo {
            get {
                return ResourceManager.GetString("regPlatoRest_M3_tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usted ha seleccionado 10 platos. 10 es el límite máximo. ¿Desea registrar la asociación? Seleccione No para cambiar su selección de platos..
        /// </summary>
        internal static string regPlatoRest_M4_info {
            get {
                return ResourceManager.GetString("regPlatoRest_M4_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selección con límite máximo.
        /// </summary>
        internal static string regPlatoRest_M4_tipo {
            get {
                return ResourceManager.GetString("regPlatoRest_M4_tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platos asociados correctamente..
        /// </summary>
        internal static string regPlatoRest_M5_info {
            get {
                return ResourceManager.GetString("regPlatoRest_M5_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asociación exitosa.
        /// </summary>
        internal static string regPlatoRest_M5_tipo {
            get {
                return ResourceManager.GetString("regPlatoRest_M5_tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platos disponibles:.
        /// </summary>
        internal static string regPlatoRest_platos {
            get {
                return ResourceManager.GetString("regPlatoRest_platos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platos asociados:.
        /// </summary>
        internal static string regPlatoRest_platosAso {
            get {
                return ResourceManager.GetString("regPlatoRest_platosAso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurantes disponibles:.
        /// </summary>
        internal static string regPlatoRest_restaurante {
            get {
                return ResourceManager.GetString("regPlatoRest_restaurante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de Plato por Restaurante.
        /// </summary>
        internal static string regPlatoRest_titulo {
            get {
                return ResourceManager.GetString("regPlatoRest_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección del Restaurante:.
        /// </summary>
        internal static string regRest_direccion {
            get {
                return ResourceManager.GetString("regRest_direccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado del Restaurante:.
        /// </summary>
        internal static string regRest_estado {
            get {
                return ResourceManager.GetString("regRest_estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identificación del Restaurante:.
        /// </summary>
        internal static string regRest_id {
            get {
                return ResourceManager.GetString("regRest_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llene todos los apartados para registrar un restaurante..
        /// </summary>
        internal static string regRest_instrucciones {
            get {
                return ResourceManager.GetString("regRest_instrucciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Restaurante:.
        /// </summary>
        internal static string regRest_nombre {
            get {
                return ResourceManager.GetString("regRest_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono del Restaurante:.
        /// </summary>
        internal static string regRest_telefono {
            get {
                return ResourceManager.GetString("regRest_telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro de Restaurante.
        /// </summary>
        internal static string regRest_titulo {
            get {
                return ResourceManager.GetString("regRest_titulo", resourceCulture);
            }
        }
    }
}
